### PR TITLE
use blade view to allow customization

### PR DESCRIPTION
**Pull request by Gummibeer**
solves #34

### CODE REVIEW

**Comment by freekmurze** [comment]
Ah, I understand your question now. 

Thank you for this!

**Comment by Gummibeer** [comment]
@freekmurze happy to hear! :) I thought that this is the most useful way to allow everyone to customize whatever they want/need.

**Comment by Gummibeer** [comment]
Packagist has some downtimes atm - can you take a look if you can manually update it? Atm the new `v2.2.0` is missing. :/
https://packagist.org/packages/spatie/laravel-blade-javascript

**Comment by freekmurze** [comment]
Spinning...

screen shot 2018-05-07 at 17 32 50

**Pull request merged**
